
version: 2

models:

    - name: stg_intercom__conversations
      description: "skello premiere table"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: stg_intercom__conversations_parts
      description: "skello deuxieme table"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
